const transaction = {
  investorId: 'string;',
  orderType: 'string;',
  orderId: 'string;',
  transferId: 'string;',
  playerId: 'string;',
  profileId: 'string;',
  fullName: 'string;',
  title: 'string;',
  subtext: 'string | null;',
  amount: 'number;',
  shares: 'number;',
  transferStatus: 'string;',
  transferType: 'string;',
  transactionTimestamp: 'number;',
  transactionTimestampSeconds: 'number;',
  teamNameAbbrev: 'string | null;',
  limitPrice: 'number | null;',
  marketMakerId: 'string;',
  status: 'StatusType;',
  sumOfSharesTransacted: 'number;',
  avgSharePrice: 'number;',
  transactionFee: 'number;',
  validUntilDate: 'firebase.firestore.Timestamp;',
}

const transactionBackup = {
  investorId: 'string;',
  orderType: 'string;',
  orderId: 'string;',
  transferId: 'string;',
  playerId: 'string;',
  profileId: 'string;',
  fullName: 'string;',
  title: 'string;',
  subtext: 'string | null;',
  amount: 'number;',
  shares: 'number;',
  transferStatus: 'string;',
  transferType: 'string;',
  transactionTimestamp: 'number;',
  transactionTimestampSeconds: 'number;',
  teamNameAbbrev: 'string | null;',
  limitPrice: 'number | null;',
  marketMakerId: 'string;',
  status: 'StatusType;',
  sumOfSharesTransacted: 'number;',
  avgSharePrice: 'number;',
  transactionFee: 'number;',
  validUntilDate: 'firebase.firestore.Timestamp;',
}